import { Analytics } from "../../types/tables";
import { Expressions } from "../expressions";
import type { SimpleQueryConfig } from "../types";

export const TrafficBuilders: Record<string, SimpleQueryConfig> = {
	// SQL output only; parseReferrers plugin adds referrer/source/domain/referrer_type/parsed_referrer at runtime.
	top_referrers: {
		meta: {
			title: "Top Referrers",
			description:
				"Top external websites and domains that drive traffic to your site, excluding direct visits.",
			category: "Acquisition",
			tags: ["referrers", "traffic sources", "external", "backlinks"],
			output_fields: [
				{
					name: "name",
					type: "string",
					label: "Referrer Domain",
					description: "The referring domain or website",
				},
				{
					name: "pageviews",
					type: "number",
					label: "Pageviews",
					description: "Total pageviews from this referrer",
				},
				{
					name: "visitors",
					type: "number",
					label: "Visitors",
					description: "Unique visitors from this referrer",
				},
				{
					name: "percentage",
					type: "number",
					label: "Traffic %",
					description: "Percentage of total referral traffic",
					unit: "%",
				},
			],
			default_visualization: "table",
			supports_granularity: ["hour", "day"],
			version: "1.0",
		},
		table: Analytics.events,
		fields: [
			`${Expressions.referrer.normalized} as name`,
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: [
			"referrer != ''",
			"referrer IS NOT NULL",
			"event_name = 'screen_view'",
			"domain(referrer) != '{websiteDomain}'",
			"NOT domain(referrer) ILIKE '%.{websiteDomain}'",
			"domain(referrer) NOT IN ('localhost', '127.0.0.1')",
		],
		groupBy: ["name"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
		],
		customizable: true,
		plugins: {
			deduplicateReferrers: true,
			parseReferrers: true,
			sessionAttribution: true,
		},
	},

	utm_sources: {
		meta: {
			title: "UTM Sources",
			description:
				"Traffic breakdown by UTM source parameters from your marketing campaigns and tracked links.",
			category: "Acquisition",
			tags: ["utm", "campaigns", "marketing", "sources"],
			output_fields: [
				{
					name: "name",
					type: "string",
					label: "UTM Source",
					description: "The UTM source parameter value",
				},
				{
					name: "pageviews",
					type: "number",
					label: "Pageviews",
					description: "Total pageviews from this source",
				},
				{
					name: "visitors",
					type: "number",
					label: "Visitors",
					description: "Unique visitors from this source",
				},
				{
					name: "percentage",
					type: "number",
					label: "Traffic %",
					description: "Percentage of total UTM traffic",
					unit: "%",
				},
			],
			default_visualization: "table",
			supports_granularity: ["hour", "day"],
			version: "1.0",
		},
		table: Analytics.events,
		fields: [
			"utm_source as name",
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: ["utm_source != ''", "event_name = 'screen_view'"],
		groupBy: ["utm_source"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
		],
		customizable: true,
		plugins: {
			sessionAttribution: true,
		},
	},

	utm_mediums: {
		table: Analytics.events,
		fields: [
			"utm_medium as name",
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: ["utm_medium != ''", "event_name = 'screen_view'"],
		groupBy: ["utm_medium"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
		],
		customizable: true,
		plugins: {
			sessionAttribution: true,
		},
	},

	utm_campaigns: {
		meta: {
			title: "UTM Campaigns",
			description:
				"Performance breakdown by UTM campaign parameters to track individual marketing campaign effectiveness.",
			category: "Acquisition",
			tags: ["utm", "campaigns", "marketing", "performance"],
			output_fields: [
				{
					name: "name",
					type: "string",
					label: "Campaign Name",
					description: "The UTM campaign parameter value",
				},
				{
					name: "pageviews",
					type: "number",
					label: "Pageviews",
					description: "Total pageviews from this campaign",
				},
				{
					name: "visitors",
					type: "number",
					label: "Visitors",
					description: "Unique visitors from this campaign",
				},
				{
					name: "percentage",
					type: "number",
					label: "Traffic %",
					description: "Percentage of total campaign traffic",
					unit: "%",
				},
			],
			default_visualization: "table",
			supports_granularity: ["hour", "day"],
			version: "1.0",
		},
		table: Analytics.events,
		fields: [
			"utm_campaign as name",
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: ["utm_campaign != ''", "event_name = 'screen_view'"],
		groupBy: ["utm_campaign"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
		],
		customizable: true,
		plugins: {
			sessionAttribution: true,
		},
	},

	utm_terms: {
		meta: {
			title: "UTM Terms",
			description:
				"Traffic breakdown by UTM term parameters, typically used for keyword tracking in paid campaigns.",
			category: "Acquisition",
			tags: ["utm", "campaigns", "keywords", "terms"],
			output_fields: [
				{
					name: "name",
					type: "string",
					label: "UTM Term",
					description: "The UTM term parameter value",
				},
				{
					name: "pageviews",
					type: "number",
					label: "Pageviews",
					description: "Total pageviews from this term",
				},
				{
					name: "visitors",
					type: "number",
					label: "Visitors",
					description: "Unique visitors from this term",
				},
				{
					name: "percentage",
					type: "number",
					label: "Traffic %",
					description: "Percentage of total UTM traffic",
					unit: "%",
				},
			],
			default_visualization: "table",
			supports_granularity: ["hour", "day"],
			version: "1.0",
		},
		table: Analytics.events,
		fields: [
			"utm_term as name",
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: [
			"utm_term != ''",
			"utm_term IS NOT NULL",
			"event_name = 'screen_view'",
		],
		groupBy: ["utm_term"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
			"utm_term",
		],
		customizable: true,
	},

	utm_content: {
		meta: {
			title: "UTM Content",
			description:
				"Traffic breakdown by UTM content parameters, used to differentiate similar content or links within the same campaign.",
			category: "Acquisition",
			tags: ["utm", "campaigns", "content", "creative"],
			output_fields: [
				{
					name: "name",
					type: "string",
					label: "UTM Content",
					description: "The UTM content parameter value",
				},
				{
					name: "pageviews",
					type: "number",
					label: "Pageviews",
					description: "Total pageviews from this content",
				},
				{
					name: "visitors",
					type: "number",
					label: "Visitors",
					description: "Unique visitors from this content",
				},
				{
					name: "percentage",
					type: "number",
					label: "Traffic %",
					description: "Percentage of total UTM traffic",
					unit: "%",
				},
			],
			default_visualization: "table",
			supports_granularity: ["hour", "day"],
			version: "1.0",
		},
		table: Analytics.events,
		fields: [
			"utm_content as name",
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: [
			"utm_content != ''",
			"utm_content IS NOT NULL",
			"event_name = 'screen_view'",
		],
		groupBy: ["utm_content"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
			"utm_content",
		],
		customizable: true,
	},

	// SQL output only; parseReferrers plugin adds referrer/source/domain/referrer_type/parsed_referrer at runtime.
	traffic_sources: {
		meta: {
			title: "Traffic Sources",
			description:
				"Traffic breakdown by direct visits and referring sources, with self-referrals folded into Direct.",
			category: "Acquisition",
			tags: ["traffic sources", "direct", "referrers", "acquisition"],
			output_fields: [
				{
					name: "name",
					type: "string",
					label: "Source",
					description: "The traffic source name or referrer domain",
				},
				{
					name: "pageviews",
					type: "number",
					label: "Pageviews",
					description: "Total pageviews from this source",
				},
				{
					name: "visitors",
					type: "number",
					label: "Visitors",
					description: "Unique visitors from this source",
				},
				{
					name: "percentage",
					type: "number",
					label: "Traffic %",
					description: "Percentage of all source-attributed traffic",
					unit: "%",
				},
			],
			default_visualization: "table",
			supports_granularity: ["hour", "day"],
			version: "1.0",
		},
		table: Analytics.events,
		fields: [
			`${Expressions.referrer.sourceWithDirect()} as name`,
			"COUNT(*) as pageviews",
			"uniq(anonymous_id) as visitors",
		],
		percentageOf: { of: "visitors" },
		where: ["event_name = 'screen_view'"],
		groupBy: ["name"],
		orderBy: "visitors DESC",
		limit: 100,
		timeField: "time",
		allowedFilters: [
			"path",
			"query_string",
			"country",
			"device_type",
			"browser_name",
			"os_name",
			"referrer",
			"utm_source",
			"utm_medium",
			"utm_campaign",
		],
		customizable: true,
		plugins: {
			deduplicateReferrers: true,
			parseReferrers: true,
			sessionAttribution: true,
		},
	},
};
