CREATE TABLE IF NOT EXISTS analytics.events
(
	`id` UUID,
	`client_id` String,
	`event_name` String,
	`anonymous_id` String,
	`time` DateTime64(3, 'UTC'),
	`session_id` String,
	`referrer` Nullable(String),
	`url` String,
	`path` String,
	`title` Nullable(String),
	`ip` String,
	`user_agent` String,
	`browser_name` Nullable(String),
	`browser_version` Nullable(String),
	`os_name` Nullable(String),
	`os_version` Nullable(String),
	`device_type` Nullable(String),
	`device_brand` Nullable(String),
	`device_model` Nullable(String),
	`viewport_size` Nullable(String),
	`language` Nullable(String),
	`timezone` Nullable(String),
	`time_on_page` Nullable(Float32),
	`country` Nullable(String),
	`region` Nullable(String),
	`city` Nullable(String),
	`utm_source` Nullable(String),
	`utm_medium` Nullable(String),
	`utm_campaign` Nullable(String),
	`utm_term` Nullable(String),
	`utm_content` Nullable(String),
	`gclid` Nullable(String),
	`dom_ready_time` Nullable(Int32),
	`ttfb` Nullable(Int32),
	`request_time` Nullable(Int32),
	`render_time` Nullable(Int32),
	`scroll_depth` Nullable(Float32),
	`interaction_count` Nullable(Int16),
	`page_count` UInt8 DEFAULT 1,
	`properties` String,
	`created_at` DateTime64(3, 'UTC'),
	`timestamp` DateTime64(3) DEFAULT toDate(time),
	`profile_id` String DEFAULT '',
	INDEX idx_session_id session_id TYPE bloom_filter(0.01) GRANULARITY 1,
	INDEX idx_anonymous_id anonymous_id TYPE bloom_filter(0.01) GRANULARITY 1,
	INDEX idx_path path TYPE bloom_filter(0.02) GRANULARITY 1,
	INDEX idx_profile_id profile_id TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/analytics_events', '{replica}')
PARTITION BY toYYYYMM(time)
ORDER BY (client_id, time, id)
SETTINGS index_granularity = 8192
