import { defineNuxtPlugin, useRuntimeConfig } from "#app";
import {
	clear,
	createScript,
	detectClientId,
	flush,
	getAnonymousId,
	getSessionId,
	getTracker,
	getTrackingIds,
	getTrackingParams,
	isScriptInjected,
	isTrackerAvailable,
	track,
	trackError,
} from "@databuddy/sdk";
import { createFlagsPlugin } from "@databuddy/sdk/vue";

export default defineNuxtPlugin((nuxtApp) => {
	const config = useRuntimeConfig().public.databuddy;
	const clientId = detectClientId(config.clientId);

	if (!clientId || config.disabled) {
		return;
	}

	if (!isScriptInjected()) {
		document.head.appendChild(createScript({ ...config, clientId }));
	}

	// SPA navigation: fire a screen_view on every client-side route change.
	// Skip the first invocation — the CDN tracker already records the landing
	// page view on initialisation, so firing again here would double-count it.
	let initialPageFinished = false;
	nuxtApp.hook("page:finish", () => {
		if (!initialPageFinished) {
			initialPageFinished = true;
			return;
		}
		window.db?.screenView();
	});

	// Auto-track Vue component errors when trackErrors is enabled.
	if (config.trackErrors) {
		nuxtApp.hook(
			"vue:error",
			(error: unknown, _instance: unknown, info: string) => {
				trackError(error instanceof Error ? error.message : String(error), {
					stack:
						error instanceof Error ? (error.stack ?? undefined) : undefined,
					error_type: info,
				});
			}
		);
	}

	if (config.flags) {
		nuxtApp.vueApp.use(createFlagsPlugin(config.flags));
	}

	// Expose $databuddy on the Nuxt app for Options API components and templates.
	// TypeScript types are generated by addTypeTemplate in the module.
	const setGlobalProperties = (properties: Record<string, unknown>) => {
		window.db?.setGlobalProperties(properties);
	};

	const screenView = (properties?: Record<string, unknown>) => {
		window.db?.screenView(properties);
	};

	return {
		provide: {
			databuddy: {
				track,
				trackError,
				clear,
				flush,
				getTracker,
				isTrackerAvailable,
				getAnonymousId,
				getSessionId,
				getTrackingIds,
				getTrackingParams,
				setGlobalProperties,
				screenView,
			},
		},
	};
});
